# ns__file unit: standard, comp: .nycrc.yml */
# ns__custom_start testCoverageThresholds */
check-coverage: true
branches: 2
lines: 40
functions: 8
statements: 40
# ns__custom_end testCoverageThresholds */
