/* ns__file unit: static-command, comp: chase.ts */
/*
* This file is autogenerated using the easy-oclif-cli template with ns-flip. Please view
* the instructions for this code base at meta/instructions.md.
*/

/* ns__start_section imports */
import {Command, flags} from '@oclif/command'

/* ns__custom_start customImports */
import {removeCodeModelDiscrepancies} from '../custom/templates/discrepancies/removeCodeModelDiscrepancies'

const {resolveDir} = require('magicalstrings').resolveDir
const {suffixes} = require('magicalstrings').constants
const {dingKats} = require('magicalstrings').constants.types.dingKats
/* ns__custom_end customImports */
/* ns__end_section imports */

export default class Chase extends Command {
static description = `compare generated code to your model, changing both until you've replicated the model with your template
`

static examples = [
/* ns__custom_start examples */
  `$ copykat chase sampleTemplateDir
`,
/* ns__custom_end examples */
]

static flags = {
  help: flags.help({char: 'h'}),
}

static args = [
  {
    name: 'template',
    description: 'the path to your template',
    required: true,
  },
]

async run() {
  const {args} = this.parse(Chase)

  const {template} = args
  /* ns__custom_start run */
  const finalTemplateDir = resolveDir(template)
  const code = finalTemplateDir + suffixes.SAMPLE_DIR
  const model = finalTemplateDir + suffixes.MODEL_DIR

  try {
    await removeCodeModelDiscrepancies(
      finalTemplateDir, code, model
    )
  } catch (error) {
    this.log(error)
    this.error(dingKats.ERROR + ` cannot compare directories: ${error}`)
  }

  /* ns__custom_end run */
}
}
